### PR TITLE
Add insert newline option

### PR DESCRIPTION
**Pull request by bynect**
Inserts a blank line when saving, if the last line is not already blank. Also rewrite calculate_len_line_number to not depend on sprintf (this should be much better, no buffer or formatting involved).

All tested and seems to work. Also I have done a little bit of refactoring

### CODE REVIEW

**Comment by bynect** [comment]
This is also a step forward to the [editorconfig](https://editorconfig-specification.readthedocs.io/#supported-pairs) specification

**Comment by arthurbacci** [comment]
ironic
ironicous
lol

**Comment by arthurbacci** [comment]
Accepted, thanks for the Pull Request!

**Comment by arthurbacci** [comment]
You should not use `new_line` function. It is made for splitting a line in two, not for creating a line.

**Comment by arthurbacci** [comment]
Anyway, I fixed the overflows in the `prompt-to-quit` function.

**Comment by bynect** [comment]
> You should not use `new_line` function. It is made for splitting a line in two, not for creating a line.

I was unsure about that, thank you

**Pull request merged**
