### PR TITLE
Add syntax highlighting for numbers

### PR DESCRIPTION
**Pull request by bynect**
Seems to work fine, I am unsure about the color of numbers, for now I have set it to 0x30.

### CODE REVIEW

**Comment by bynect** [comment]
Closes #34

**Comment by bynect** [comment]
I have reduced a little bit the lines of code

**Comment by arthurbacci** [comment]
Coulor is `int` in case of expansion of the number of colours. Ex: add true colour.

**Comment by arthurbacci** [comment]
Anyway, accepted.

**Comment by arthurbacci** [comment]
Thanks for the Pull Request!

**Pull request merged**
