### PR TITLE
Highly optimize syntaxHighlight

### PR DESCRIPTION
**Pull request by bynect**
Currently syntaxHighlight is a fully synchronous function that takes a lot of time to run on very large file, that are unusably slow to modify/load/update. The aim of this pr is to transform syntaxHighlight from a heavy blocking function to a asynchron-ish function that is executed cooperatively with the main loop while no input from the user is available.

## how it works
Change the way the main loop and syntaxHighlight interacts. Now syntaxHighlight is preemptively interrupted and it is not a blocking function anymore, behaving more similarly to a coroutine/asynchronous function than a normal one. When syntaxHighlight is called it start a timer that after `SYNTAX_TIMEOUT` microseconds sends a `SIGALRM` that sets the flag `syntax_yield` to true through a signal handler, when `syntax_yield` is set syntaxHighlight will save its state in a struct SHSTATE and return. Every subsequent call to syntaxHighlight  will restore the saved context and continue, and when the highlighting is done syntaxHighlight will return `SYNTAX_END`  (when yielding syntaxHighlight returns `SYNTAX_TODO`). Note that syntaxHighlight  always returns either a `SYNTAX_END`  or `SYNTAX_TODO` ~~with a `longjmp` to the main loop~~. 

If the syntax needs to be updated (opened a new file, changed syntax descriptor, etc) the flag `syntax_change` is set and the main loop will automatically prepare and call `syntaxHighlight`.
~~`syntax_env` is the `setjmp` buffer used to jump between syntaxHighlight and the main loop.~~

## notes
* I don't know why, but when compiling with asan this is much slower than with the normal compilation flags.

* When syntaxHighlight hasn't yet highlighted a line, that line will be shown as white to the user. (a white line is better than having to wait for it to finish the entire file without handling any input). 

* ncurses is not set in nonblocking mode with a timeout of `INPUT_TIMEOUT`.

## references
This helped me to come up with this solution: http://enki-editor.org/2014/08/22/Syntax_highlighting.html
Other useful links:
* https://www.gnu.org/software/libc/manual/html_node/Setting-an-Alarm.html
* http://man.docs.sk/3ncurses/raw.html

### CODE REVIEW

**Comment by bynect** [comment]
The next thing to do is to don't call syntaxHighlight on the entire file every time a modification is made by the user, but to update the highlight only on the part that was modified

**Comment by bynect** [comment]
If we associate a SHSTATE for every line we won't need to run syntaxHighlight from the start to the end of file every time, at the cost of some extra memory for every line

**Comment by arthurbacci** [comment]
Perfect. I will do a commit soon for fixing an issue that I created: Updating the syntax highlighting only when a change is made breaks the matching-brackets.

**Comment by arthurbacci** [comment]
Thanks for the Pull Request!

**Pull request merged**
