### PR TITLE
(Try to) fix Utf8

### PR DESCRIPTION
**Pull request by bynect**
The aim of this pr is to add a way to validate utf8 and to handle "gracefully" invalid sequences, by replacing them with a [placeholder character](https://www.compart.com/en/unicode/U+FFFD).

### CODE REVIEW

**Comment by bynect** [comment]
I was not sure on how to handle high/low surrogates so I added a config flag, but in most cases they should be interpreted as invalid

**Comment by bynect** [comment]
This may also be related with #40

**Comment by arthurbacci** [comment]
Why to check twice instead of checking just on utf8ToMultibyte and replacing it if it's invalid?

**Comment by bynect** [comment]
> Why to check twice instead of checking just on utf8ToMultibyte and replacing it if it's invalid?

Where?

**Comment by arthurbacci** [comment]
You can detect it only when displaying.

**Comment by bynect** [comment]
> You can detect it only when displaying.

You have to check when reading because the next characters shouldn't be consumed if the codepoint is malformed. The check is just used to ungetc the characters. In this way malformed utf8 can be stored without losing its original value, at least for what I have tried.

**Comment by bynect** [comment]
Now I am adding validation for user input

**Pull request merged**
