### PR TITLE
Add parenthesis automatch

### PR DESCRIPTION
**Pull request by bynect**
Add parenthesis automatch and its config dialog

### CODE REVIEW

**Comment by arthurbacci** [comment]
I think
```c
            if (match != NULL) {
                expandLine(cy, 2);
                memmove(&lines[cy].data[cx + 1], &lines[cy].data[cx], (lines[cy].length - cx) * sizeof(uchar32_t));

                lines[cy].data[cx] = c;
                lines[cy].data[cx + 1] = config.current_syntax->match[1][match - config.current_syntax->match[0]];
                ++lines[cy].length;
                goto end; //skip to the end
            }
```
can be replaced with:
```c
            if (match != NULL) {
                process_keypress(config.current_syntax->match[1][match - config.current_syntax->match[0]]);
                goto end; //skip to the end
            }
```

**Comment by bynect** [comment]
Seems to work fine now

**Comment by arthurbacci** [comment]
Try always to respect the **fewer lines** principle. Otherwise, ted would be of the size of nano.

**Comment by arthurbacci** [comment]
Accepted, thanks for the Pull Request!

**Pull request merged**
