### PR TITLE
Improve syntaxes

### PR DESCRIPTION
**Pull request by bynect**
Add more keywords, constant, etc. to create "real life" syntax highlighting.

### CODE REVIEW

**Comment by bynect** [comment]
Don't merge yet, I am working on the c/c++ descriptor now

**Comment by arthurbacci** [comment]
Wow

**Comment by bynect** [comment]
> Wow

In your opinion is better to divide the C and C++ descriptors or to maintain an unified one?
(Differences: class public private protected constexpr restricted etc)

**Comment by arthurbacci** [comment]
I think a unified one is good. Most of the text editors have a unified one.

**Comment by bynect** [comment]
> I think a unified one is good. Most of the text editors have a unified one.

I looked up for the different keywords and it seems like C++ has a tons more keywords than c. https://en.cppreference.com/w/c/keyword
https://en.cppreference.com/w/cpp/keyword

Probably separating is better at this point

**Comment by arthurbacci** [comment]
In this case, I think it would be good to separate. But there's a problem: `.h` is used both by C and C++

**Comment by bynect** [comment]
> In this case, I think it would be good to separate. But there's a problem: `.h` is used both by C and C++

Yea, sometimes even on github my c headers are labelled as c++. What do you think I should do in this case?

**Comment by bynect** [comment]
For now I have added only C (up to C11) keywords to c_cpp_kwd. Now, should I add C++ keywords too or prepare a different descriptor?

**Comment by arthurbacci** [comment]
I think it's better to prepare a different one.

**Pull request merged**
